# -*- coding: utf-8 -*-
"""Rag_url.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXlemToX4fY9X6VICO10ReL9Kj6BrcbD
"""

# !pip install langchain langchain-community langchain-core langchain-experimental langgraph langsmith
# !pip install  langchain_chroma
# !pip install  langchain_chroma
# !pip install -U langchain langchain-community
# !pip install -qU langchain-groq

from langchain_community.document_loaders import WebBaseLoader
from sentence_transformers import SentenceTransformer
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
import uuid
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.prompts import MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
from langchain_classic.chains import create_history_aware_retriever
from langchain_groq import ChatGroq
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_classic.chains import create_retrieval_chain
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
import os
from langchain_classic.chains.combine_documents import create_stuff_documents_chain

load_dotenv()
api_key = os.getenv("GROQ_API_KEY")
ef = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
os.environ["USER_AGENT"] = "MyRAGBot/1.0 (learning project)"
def create_new_directory(url, name, vectore_dire, chunksize=1000,chunklap=100):
  loader = WebBaseLoader(url,  bs_get_text_kwargs={"strip": True, "separator": "\n"})
  docs = loader.load()
  text_splitter = RecursiveCharacterTextSplitter(
      chunk_size = chunksize,
      chunk_overlap = chunklap,
      length_function = len,
      separators=["\n\n","\n"," ",""]
  )
  chunks = text_splitter.split_documents(docs)

  vectore_store = Chroma(
      collection_name=name,
      embedding_function=ef,
      persist_directory=vectore_dire
  )

  uuids = [str(uuid.uuid4()) for _ in range(len(chunks))]
  vectore_store.add_documents(chunks,ids=uuids)
  retriever = vectore_store.as_retriever(
    search_kwargs={"k": 3})

  return vectore_store , retriever

def existing(name, vectore_dire):
  vectore_store = Chroma(
      collection_name=name,
      embedding_function=ef,
      persist_directory=vectore_dire
  )
  retriever = vectore_store.as_retriever(
    search_kwargs={"k": 3})

  return vectore_store , retriever

llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=api_key , max_tokens=500 , reasoning_effort=None)

contextualize_q_system_prompt = """Given a chat history and the latest user question
which might reference context in the chat history, formulate a standalone question
which can be understood without the chat history. Do NOT answer the question,
just reformulate it if needed and otherwise return it as is."""

contextualize_q_prompt = ChatPromptTemplate.from_messages([
    ("system", contextualize_q_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}"),
])

def creating_history_retriver(retriever):
  history_retriver = create_history_aware_retriever(
      llm,retriever,contextualize_q_prompt
  )
  return history_retriver

qa_system_prompt = """You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Use three sentences maximum and keep the answer concise.

Context: {context}"""
qa_prompt = ChatPromptTemplate.from_messages([
    ("system",qa_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}")]

)

chat_history = []
def chain(history_retriver,Question):
  global chat_history
  stuff = create_stuff_documents_chain(llm ,qa_prompt)
  chain = create_retrieval_chain(history_retriver,stuff)
  result = chain.invoke({
      "chat_history": chat_history,
      "input": Question
  })
  chat_history.extend([
      HumanMessage(content=Question),
      AIMessage(content=result['answer'])
  ])
  chat_history = chat_history[-10:]
  return result["answer"]

import hashlib

current_url = None
def ask(Url:str, Question):
  global current_url
  # Generate a valid collection name by hashing the URL
  name = hashlib.md5(Url.encode('utf-8')).hexdigest()
  vectore_dire = ".data/vectorestore"
  if current_url == Url:
   vectore_store , retriver = existing(name=name, vectore_dire=vectore_dire)
  else:
    vectore_store , retriver = create_new_directory(url=Url,name=name, vectore_dire=vectore_dire)
    if current_url is not None:
      
      prev_url_hash = hashlib.md5(current_url.encode('utf-8')).hexdigest()
      try:
          vectore_store._client.delete_collection(name=prev_url_hash)
      except Exception as e:
          print(f"Could not delete collection {prev_url_hash}: {e}")

  history_retriver = creating_history_retriver(retriever=retriver)
  response = chain(history_retriver=history_retriver,Question=Question)
  global collections
  native_client = vectore_store._client
  collections = native_client.list_collections()


  current_url = Url

  return response

# response = ask(Url="https://en.wikipedia.org/wiki/Dog",Question="what is the dog")
# print(response)